import { Payment, columns } from "./columns";
import { DataTable } from "./data-table";

const getData = async (): Promise<Payment[]> => {
  return [
    {
      id: "728ed521",
      userId: 183,
      amount: 134,
      status: "در انتظار",
      fullname: "علی رضایی",
      email: "ali.rezaei@gmail.com",
    },
    {
      id: "728ed522",
      userId: 427,
      amount: 124,
      status: "موفق",
      fullname: "سارا محمدی",
      email: "sara.mohammadi@gmail.com",
    },
    {
      id: "728ed523",
      userId: 592,
      amount: 167,
      status: "موفق",
      fullname: "مهدی کریمی",
      email: "mehdi.karimi@gmail.com",
    },
    {
      id: "728ed524",
      userId: 316,
      amount: 156,
      status: "ناموفق",
      fullname: "نگار احمدی",
      email: "negar.ahmadi@gmail.com",
    },
    {
      id: "728ed525",
      userId: 748,
      amount: 145,
      status: "موفق",
      fullname: "فاطمه حسینی",
      email: "fatemeh.hosseini@gmail.com",
    },
    {
      id: "728ed526",
      userId: 205,
      amount: 189,
      status: "در انتظار",
      fullname: "رضا کاظمی",
      email: "reza.kazemi@gmail.com",
    },
    {
      id: "728ed527",
      userId: 861,
      amount: 178,
      status: "موفق",
      fullname: "مریم جعفری",
      email: "maryam.jafari@gmail.com",
    },
    {
      id: "728ed528",
      userId: 374,
      amount: 190,
      status: "موفق",
      fullname: "حسین مرادی",
      email: "hossein.moradi@gmail.com",
    },
    {
      id: "728ed529",
      userId: 639,
      amount: 134,
      status: "ناموفق",
      fullname: "زهرا صادقی",
      email: "zahra.sadeghi@gmail.com",
    },
    {
      id: "728ed52a",
      userId: 951,
      amount: 543,
      status: "موفق",
      fullname: "امیر عباسی",
      email: "amir.abbasi@gmail.com",
    },
    {
      id: "728ed52b",
      userId: 482,
      amount: 234,
      status: "در انتظار",
      fullname: "الهام نوری",
      email: "elham.nouri@gmail.com",
    },
    {
      id: "728ed52c",
      userId: 127,
      amount: 345,
      status: "موفق",
      fullname: "محمد قربانی",
      email: "mohammad.ghorbani@gmail.com",
    },
    {
      id: "728ed52d",
      userId: 706,
      amount: 335,
      status: "ناموفق",
      fullname: "حدیث رستمی",
      email: "hadis.rostami@gmail.com",
    },
    {
      id: "728ed52e",
      userId: 593,
      amount: 664,
      status: "در انتظار",
      fullname: "پویا شریفی",
      email: "pouya.sharifi@gmail.com",
    },
    {
      id: "728ed52f",
      userId: 218,
      amount: 332,
      status: "موفق",
      fullname: "نازنین اکبری",
      email: "nazanin.akbari@gmail.com",
    },
    {
      id: "728ed52g",
      userId: 845,
      amount: 413,
      status: "ناموفق",
      fullname: "بهرام یوسفی",
      email: "bahram.yousefi@gmail.com",
    },
    {
      id: "728ed52h",
      userId: 369,
      amount: 345,
      status: "در انتظار",
      fullname: "شبنم موسوی",
      email: "shabnam.mousavi@gmail.com",
    },
    {
      id: "728ed52i",
      userId: 514,
      amount: 754,
      status: "موفق",
      fullname: "آرمان حیدری",
      email: "arman.heydari@gmail.com",
    },
    {
      id: "728ed52j",
      userId: 932,
      amount: 643,
      status: "ناموفق",
      fullname: "لیلا مرادی",
      email: "leila.moradi@gmail.com",
    },
    {
      id: "728ed52k",
      userId: 271,
      amount: 543,
      status: "در انتظار",
      fullname: "سعید کمالی",
      email: "saeed.kamali@gmail.com",
    },
    {
      id: "728ed52l",
      userId: 687,
      amount: 324,
      status: "موفق",
      fullname: "پریسا رحیمی",
      email: "parisa.rahimi@gmail.com",
    },
    {
      id: "728ed52m",
      userId: 403,
      amount: 123,
      status: "در انتظار",
      fullname: "کیان نوروزی",
      email: "kian.nowrouzi@gmail.com",
    },
    {
      id: "728ed52n",
      userId: 159,
      amount: 422,
      status: "ناموفق",
      fullname: "مونا بهرامی",
      email: "mona.bahrami@gmail.com",
    },
    {
      id: "728ed52o",
      userId: 824,
      amount: 712,
      status: "موفق",
      fullname: "میلاد لطفی",
      email: "milad.lotfi@gmail.com",
    },
    {
      id: "728ed52p",
      userId: 536,
      amount: 360,
      status: "موفق",
      fullname: "آیدا زمانی",
      email: "ayda.zamani@gmail.com",
    },
    {
      id: "728ed52q",
      userId: 297,
      amount: 454,
      status: "در انتظار",
      fullname: "فرهاد امینی",
      email: "farhad.amini@gmail.com",
    },
    {
      id: "728ed52r",
      userId: 763,
      amount: 382,
      status: "موفق",
      fullname: "سحر ملکی",
      email: "sahar.maleki@gmail.com",
    },
    {
      id: "728ed52s",
      userId: 418,
      amount: 328,
      status: "ناموفق",
      fullname: "نوید اسدی",
      email: "navid.asadi@gmail.com",
    },
    {
      id: "728ed52t",
      userId: 690,
      amount: 250,
      status: "موفق",
      fullname: "رها طالبی",
      email: "raha.talebi@gmail.com",
    },
    {
      id: "728ed52u",
      userId: 345,
      amount: 658,
      status: "موفق",
      fullname: "یاسر حاتمی",
      email: "yaser.hatami@gmail.com",
    },
    {
      id: "728ed52v",
      userId: 902,
      amount: 691,
      status: "موفق",
      fullname: "نیلوفر شفیعی",
      email: "niloufar.shafiei@gmail.com",
    },
    {
      id: "728ed52w",
      userId: 574,
      amount: 969,
      status: "موفق",
      fullname: "سینا جعفری",
      email: "sina.jafari@gmail.com",
    },
    {
      id: "728ed52x",
      userId: 231,
      amount: 617,
      status: "ناموفق",
      fullname: "مهسا قاسمی",
      email: "mahsa.ghasemi@gmail.com",
    },
    {
      id: "728ed52y",
      userId: 658,
      amount: 173,
      status: "موفق",
      fullname: "پارسا رفیعی",
      email: "parsa.rafiei@gmail.com",
    },
    {
      id: "728ed52z",
      userId: 109,
      amount: 843,
      status: "موفق",
      fullname: "ترانه صبوری",
      email: "taraneh.sabouri@gmail.com",
    },
    {
      id: "728ed521f",
      userId: 786,
      amount: 914,
      status: "در انتظار",
      fullname: "بردیا سلطانی",
      email: "bardiya.soltani@gmail.com",
    },
  ];
};

const PaymentsPage = async () => {
  const data = await getData();
  return (
    <div className="">
      <div className="mb-8 px-4 py-2 bg-secondary rounded-md">
        <h1 className="font-semibold">همه پرداخت‌ها</h1>
      </div>
      <DataTable columns={columns} data={data} />
    </div>
  );
};

export default PaymentsPage;
